### ISSUE TITLE
Usage with QuillJS

### ISSUE THREAD

**Issue by rawkode** [Teamwork/ot-rich-text#1]
Is it possible to use this with QuillJS? I notice the format utilises arrays, rather than the Delta format, that `rich-text` adheres to.

Is there a simple way to transform this, or will I need to write my own code for that?

**Comment by gkubisa** [comment]
> Is it possible to use this with QuillJS?

ot-rich-text is not compatible with QuillJS, so you can't use it directly. If you use QuillJS and need specific features from ot-rich-text, you could consider porting those features to rich-text, instead of converting snapshots and operations between types.

> Is there a simple way to transform this, or will I need to write my own code for that?

You'd need to write your own code to convert ot-rich-text to rich-text and vice versa. The conversion is simple but performance might be an issue.

**Comment by rawkode** [comment]
No problem. I'll clone the presence stuff over to `rich-text` :+1:
